### ISSUE TITLE
TableView on Types tab not scrollable

### ISSUE THREAD

**Issue by geberl** [geberl/swift-localstorage#19]
On iPhone landscape this means the lower items are not reachable.

**Comment by femilamptey** [comment]
Hello @geberl , I'd like to handle this issue

**Comment by geberl** [comment]
@femilamptey Nice! I look forward to your pull request.

Should be pretty easy. I'd just play around with the parameters in `Main.storyboard` (Types Scene, Types Table View). And maybe the constraints are off for it as well. Bulk of the work is testing for the different device sizes and orientations.

**Comment by femilamptey** [comment]
I believe I've fixed the issue, but I can't test it out because the CommonCryptoModule keeps causing the module to fail building. I've been trying to fix it all this time, but no avail. Any help please? @geberl

**Comment by geberl** [comment]
@femilamptey Ok interesting. What does the build error say? Are you using XCode 9.3?

**Comment by femilamptey** [comment]
@geberl I'm using Xcode 9.2. Is 9.3 required?

**Comment by geberl** [comment]
@femilamptey Good question, few people know what's going on inside the depths of the `.xcodeproj` and `*.xcworkspace` packages ;) What's your error message?

**Comment by femilamptey** [comment]
It's only one error, a compiler error: No such module 'CommonCryptoModule'. I've installed the pods via the terminal already. @geberl

**Comment by geberl** [comment]
@femilamptey Which file do you open with Xcode? The blue **blue** `*.xcodeproj` file or the **white** `*.xcworkspace` one? When working with CocoaPods you always need to use the generated **white** `*.xcworkspace` file, otherwise the pods are not there (and can't be found when building).

https://stackoverflow.com/questions/29500227/getting-error-no-such-module-using-xcode-but-the-framework-is-there#33946372

This is the pod that's cause the problem by the way: https://github.com/nkukushkin/CommonCryptoModule
There's not much going on, just a few Objective C header files to make Apple's CommonCrypto library available in Swift.

**Comment by femilamptey** [comment]
@geberl It's working fine now. Thanks so much!

**Comment by femilamptey** [comment]
All done @geberl

**Comment by geberl** [comment]
@femilamptey Nice, thanks. I'll take a look on Sunday, I'm not on my mac until then.

**Comment by femilamptey** [comment]
@geberl  Hey, hope you've been good. Were you able to check it out?
