### ISSUE TITLE
CTD while extracting

### ISSUE THREAD

**Issue by HorstFreigang** [geberl/swift-localstorage#29]
Hi!

I‘ve tried your app and find it quite nice. But unfortunately I get a CTD when extracting a Zip-file. The archive is around 800 MB in size and contains 97 files. I‘m using an iPad Air 2.

Do you have any idea? Is my device too weak for that operation?

**Comment by geberl** [comment]
Probably related to #6 .

LocalStorage currently uses **SWCompression** 4.5.0 from https://github.com/tsolomko/SWCompression to allow for extracting a large number of formats (Zlib, GZip, XZ, ZIP, TAR, 7-Zip). Performance is bad though. I should maybe just use **Zip** https://github.com/marmelroy/Zip and not support all these exotic formats ...

**Comment by HorstFreigang** [comment]
Hi! Never thought about shortcuts. Thanks.
