### ISSUE TITLE
Safari and Chrome crashes after extract

### ISSUE THREAD

**Issue by zoeandersonross** [geberl/swift-localstorage#35]
Hi,

I am trying to download 100+ files to my iPad using Local Storage.

I open with Extract, press Extract, but when I go back to Safari or Chrome - it has frozen and I can’t click on anything. I have to swipe it away and reopen it every time.

Is anyone else having this issue or has anyone got a solution?

Thanks,

Zoe

**Comment by geberl** [comment]
Are you trying to extract one zip file containing 100+ files OR 100+ zip files?

In any case it looks like you're running into some resource constraint here. Extracting not via the share extension but via Local Storage's main app (on the "Types" tab) might help.

Otherwise you may be better off using Apple's **Shortcuts** app and the "Extract Archive" task there. Resource constraints don't apply in the same fashion there.

**Comment by zoeandersonross** [comment]
I'm trying to extract 100+ zip files.

How do I extract using Local Storage's Types tab? How do I download the file from Safari to have it extracted via Types tab?

How do I use the Shortcuts app to extract archive? How do I get the zip file on my iPad first?

**Comment by geberl** [comment]
Tested with the following zip file: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-8.2.1.zip (325.4mb compressed, 431.4mb extraced, 15914 items contained)

Takes longer than on my mac but works.

Steps:

1. ![IMG_0537](https://user-images.githubusercontent.com/7255425/58955216-a043f680-879b-11e9-8f70-17518e35abc7.PNG)

2. 
![IMG_0538](https://user-images.githubusercontent.com/7255425/58955289-ded9b100-879b-11e9-84c7-5aaf8317db41.PNG)

3. 
![IMG_0539](https://user-images.githubusercontent.com/7255425/58955295-e731ec00-879b-11e9-9d7e-fed26007b813.PNG)

4. 
![IMG_0540](https://user-images.githubusercontent.com/7255425/58955362-134d6d00-879c-11e9-88ec-5ad5b15d6904.PNG)

5. 
![IMG_0541](https://user-images.githubusercontent.com/7255425/58955369-18122100-879c-11e9-880f-9f5eacfc6ceb.PNG)

6. 
![IMG_0542](https://user-images.githubusercontent.com/7255425/58955378-1c3e3e80-879c-11e9-811b-809a09c84c4d.PNG)

**Comment by geberl** [comment]
I'm closing this, since extracting through the app works. And there's nothing I can do about the imposed time limits when using the share extension.
